os: linux
dist: xenial
language: java
services:
- docker
before_deploy:
- "./mvnw -B -V package"
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker build -t joengenduvel/codenature .
deploy:
  provider: script
  script: docker push joengenduvel/codenature
  on:
    branch: main
before_install:
- chmod +x mvnw
before_cache:
- rm -f  $HOME/.m2/
cache:
  directories:
  - "$HOME/.m2/"